# Generated by Django 3.2.16 on 2023-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('bronze', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('platinum', 'プラチナ'), ('diamond', 'ダイヤ')], max_length=255, unique=True)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='comparator',
            field=models.CharField(choices=[('<', 'より大きい'), ('>', 'より小さい'), ('=', '等しい'), ('<=', '以上'), ('>=', '以下')], default='<=', max_length=2),
        ),
    ]
