# Generated by Django 3.2.16 on 2023-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20230519_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BadgeTypeColor',
            new_name='BadgeType',
        ),
    ]
