# Generated by Django 3.2.16 on 2023-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_rename_badgetypecolor_badgetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='comparator',
            field=models.CharField(choices=[('<', 'より小さい'), ('>', 'より大きい'), ('==', '等しい'), ('<=', '以下'), ('>=', '以上')], default='>=', max_length=2),
        ),
    ]
