# Generated by Django 3.2.16 on 2023-05-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='activity_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activityrecord'),
        ),
    ]
